### ISSUE TITLE
Add more E2E tests

### ISSUE THREAD

**Issue by tumidi** [innodoc/innodoc-webapp#107]
- custom content
    - [ ] nav/footer links
    - [ ] footers
    - [ ] branding
- content
    - [ ] LaTeX formular rendering
    - [ ] display of sub-sections
    - [ ] breadcrumb
    - [ ] section/page links
- exercises
    - [ ] rendering
    - [ ] validation
    - [ ] hints
- [ ] TOC next/prev navigation
- [ ] search
- media query
   - [x] nav: mobile menu button
   - [x] mobile drawer menu
- translation
   - [x] content with and w/o client-side loading
   - [x] language detection (browser, cookie)
- error conditions
   - [x] 404 client-side
   - [x] 404 server-side
- basic
   - [ ] page load
   - [ ] page navigation
   - [x] section load
   - [ ] section navigation
   - [x] check basic page elements

**Comment by tumidi** [comment]
marked this issue as a duplicate of #74

**Comment by tumidi** [comment]
closed
