### ISSUE TITLE
Add E2E/browser automation tests

### ISSUE THREAD

**Issue by tumidi** [innodoc/innodoc-webapp#50]
Progress in branch `e2e`.

##### TODO

- [x] #40
- [x] Add Nightmare
- [x] Put test data in `e2e/content-data`
- [x] npm script `test:e2e`
- [x] `NightmareEnvironment`
   - [x] Spawn app server
   - [x] Spawn webserver to serve test content data
- [ ] Add e2e task to `.gitlab-ci.yml`

#### Archived: Research

Use Selenium/[WHATEVER]… and write some nice tests.

Frameworks

- https://github.com/segmentio/nightmare (electron) 16K :star:
- https://github.com/cypress-io/cypress 7K :star:
- https://github.com/nightwatchjs/nightwatch (Webdriver protocol) 8K :star:
- http://webdriver.io/ 4K :star: 
- https://devexpress.github.io/testcafe/ 5K :star:

Other interesting stuff:

- GoogleChrome/puppeteer Headless Chrome Node API
- https://github.com/segmentio/daydream chrome extension to record your actions into a nightmare or puppeteer script
- https://github.com/segmentio/niffy Perceptual diffing suite built on Nightmare

**Comment by tumidi** [comment]
Progress in branch `e2e`.

##### TODO

- Put test data in `e2e/content-data`
- npm script `test:ci-e2e`
 - Spawn webserver to serve test content data
 - Do not hard-code ports
- Add e2e task to `.gitlab-ci.yml`

**Comment by tumidi** [comment]
marked the checklist item **#40** as completed

**Comment by tumidi** [comment]
mentioned in commit 22fac91f24afc3138e1959570a931ef0b45719ef

**Comment by tumidi** [comment]
mentioned in commit caba42cb1659e088cfd4073ff0f71a9eca11d621

**Comment by tumidi** [comment]
closed via commit caba42cb1659e088cfd4073ff0f71a9eca11d621
